allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: false
  msgpackr-extract: set this to true or false
  prisma: true
  unrs-resolver: false
  workerd: set this to true or false
