/**
 * Biznes xatolarining barqaror mashina kodlari.
 * Frontend aynan shu kodlar bo'yicha ishlaydi — qiymatlarni o'zgartirmang.
 */
export const ErrorCode = {
  /* Umumiy */
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  /* Auth */
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  LOGIN_BLOCKED: 'LOGIN_BLOCKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  WRONG_PASSWORD: 'WRONG_PASSWORD',

  /* OTP */
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_NOT_PENDING: 'OTP_NOT_PENDING',
  OTP_SERVICE_UNAVAILABLE: 'OTP_SERVICE_UNAVAILABLE',

  /* Qurilmalar */
  DEVICE_LIMIT_REACHED: 'DEVICE_LIMIT_REACHED',
  DEVICE_REMOVAL_TOO_EARLY: 'DEVICE_REMOVAL_TOO_EARLY',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_CURRENT_CANNOT_BE_REMOVED: 'DEVICE_CURRENT_CANNOT_BE_REMOVED',

  /* Foydalanuvchilar */
  PHONE_TAKEN: 'PHONE_TAKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_INACTIVE: 'STORE_INACTIVE',

  /* Menejerlik */
  MANAGER_ALREADY_EXISTS: 'MANAGER_ALREADY_EXISTS',
  MANAGER_NOT_FOUND: 'MANAGER_NOT_FOUND',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
